In [44]:
import torch
from torch import nn

import torch.nn.functional as F



In [45]:
x= torch.arange(20, dtype=torch.float32).reshape(1, 20)
torch.save(x, 'x-file')
x.shape

torch.Size([1, 20])

In [46]:
x2 = torch.load('x-file')
x2
# 直接读取即可. 返回来的就是原来的那个变量.

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19.]])

In [47]:
y= torch.zeros(4)

torch.save([x, x2], 'list')
# 你可以存储任何你想要存储的格式. 包括列表,或者字典. 
# 读取回来的时候也是同理的, 需要一个变量去接收它.

p = torch.load('list')
print(p)

[tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19.]]), tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19.]])]


In [48]:
# 加载和保存模型参数
class MLP(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.out = nn.Linear(256, 10)
        
    def forward(self, x) -> torch.Tensor:
        return self.out(F.relu(self.hidden(x)))

net = MLP()
print(type(net.state_dict())) # 所有参数的
torch.save(net.state_dict(), "MLP.pt")

<class 'collections.OrderedDict'>


tensor([[-1.0845,  1.0125,  1.5647,  2.1626, -1.5772, -1.2681,  0.6972, -0.7856,
          4.4136,  1.3536]], grad_fn=<AddmmBackward0>)

In [49]:
clone = MLP() # generate instance.

clone.load_state_dict(torch.load('./MLP.pt'))

clone

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (out): Linear(in_features=256, out_features=10, bias=True)
)

In [56]:
x = torch.randn(size=(2, 20))
net(x) == clone(x) 

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])