In [1]:
# 首先导入pytorch
# 尽管名称叫做pytorch, 但是我们导入的时候实际上是导入torch
import gc

import torch

In [2]:
# 然后我们使用torch创建数据操作
# 张量表示由一个数值组成的数组，这个数组可能有多个维度。
# 具有一个轴的张量对应数学上的向量（vector）； 具有两个轴的张量对应数学上的矩阵（matrix）； 具有两个轴以上的张量没有特殊的数学名称。

# 首先是arange()作用与range()相同. 创建一个序列数据
x = torch.arange(12)
x


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# # tensor的属性:
# shape打印tensor的形状
x.shape # torch.Size([12])

torch.Size([12])

In [4]:
# size属性, Tensor中的元素总数. 即形状的所有元素成绩. 可以检查他的大小
x.size()

torch.Size([12])

In [5]:
# 数组中元素个数 
x.numel() # number of element
# 

12

In [6]:
# 改变一个张量的形状而不改变元素数量和元素值, 可以调用reshape函数.
x = x.reshape(shape=(3, 4)) # 不改变原始的形状. 返回新形状tensor对象
x
# 但是reshape其实是创建了一个视图(view)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

我们不需要通过手动指定每个维度来改变形状。 也就是说，如果我们的目标形状是（高度,宽度）， 那么在知道宽度后，高度会被自动计算得出，不必我们自己做除法。 在上面的例子中，为了获得一个3行的矩阵，我们手动指定了它有3行和4列。 幸运的是，我们可以通过-1来调用此自动计算出维度的功能。 即我们可以用x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)。

In [7]:
# 我们可以使用-1, 占位, 不过-1只能存在一个维度, 表示自动计算该维度.
x = x.reshape(shape=(2, -1))
x.shape # torch.Size([2, 6])


torch.Size([2, 6])

In [8]:
# 有时候我们需要指定全0, 或者全1数组, 
# 全1数组
torch.zeros(size=(2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
# 全0数组
torch.ones(size=(2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
# 特殊值数组
torch.full(size=(2, 3, 4), fill_value=10)
# 生成全fill_value的数组
# 我们还需要知道size=()的不同维度对应到形状到底是什么样子的. 
# size=(2, 3, 4)就是2个(3, 4)的矩阵. 

tensor([[[10, 10, 10, 10],
         [10, 10, 10, 10],
         [10, 10, 10, 10]],

        [[10, 10, 10, 10],
         [10, 10, 10, 10],
         [10, 10, 10, 10]]])

In [11]:
# 随机分布: 服从高斯分布, 我们一般是

# 运算符

In [12]:
# 对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算
# 我们可以在同一形状的任意两个张量上调用按元素操作。
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y
# 形状相同的情况下, 默认使用按照元素操作. 

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
# “按元素”方式可以应用更多的计算，包括像求幂这样的一元运算符。
torch.exp(x)
# 除了按元素计算外，我们还可以执行线性代数运算，包括向量点积和矩阵乘法。 我们将在 2.3节中解释线性代数的重点内容。

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [14]:
# 张量拼接:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
# 在后面训练时, 我们都是使用的float32类型, 进行训练, 因为float32的运算速度快.
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) # 使用2.0, 直接创建float32类型的元素
print(X, Y, sep='\n')
# 按照轴进行拼接: API: torch.cat()
torch.cat((X, Y), dim=0), # 按照dim=0, 就是行维度, 也就是竖直方向进行拼接.
torch.cat((X, Y), dim=1) # dim=1按照1维度拼接. 这里也就是列维度, 也就是水平方向拼接.

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [15]:
# 使用逻辑运算符构建二元张量, 其实也就是生成逻辑矩阵
X == Y # return a logistic matrix

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
# 求和
X.sum() # return a sigal element tensor default
# sure, is not only have sum(), but also have mean()....
# wahtever x is waht dimension, via .sum() all retuan a scalar

tensor(66.)

In [17]:
gc.collect()

0

In [18]:
# 广播机制
# 在上面的部分中，我们看到了如何在相同形状的两个张量上执行按元素操作。 在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。 这种机制的工作方式如下：首先，通过适当复制元素来扩展一个或两个数组， 以便在转换之后，两个张量具有相同的形状。 其次，对生成的数组执行按元素操作。
# 当然, 广播机制的条件, 就是运算两端Tensor不同.
# 两个Tensor, 需要满足某一维度相同, 或者某一个维度上为1. 即可使用broadcasting mechanism 即广播机制.
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b
# 显然, a, b形状不同. 此时无法直接做运算, 因此我们需要广播, 所谓广播其实也就是将数组按照一定规律进行复制. 广播后的tensor(multidimensional  array), 形状相同

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
# calculate
a + b
# 可见, a和b最终的结果就是shape is (3, 2)

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [20]:
# 索引和切片.
# 先访问行, 再访问列.
X[-1], X[1:3]
# 最后一行
# index: 1-2行. 

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [27]:
# 节省内存: 运行一些操作可能会导致为新结果重新分配内存:
before = id(Y)
Y = Y + X
id(Y) == before
# False, 可见, 这种数据操作改变重新复制了Y的引用. 

False

In [28]:
# 执行原地操作非常简单:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))